# Specify docker image
image: debian:stretch

stages:
  - tarballs

build-release:
  stage: tarballs
  only:
    - tags
  script:
    - VERSION=$(grep '%' Changelog.md | head -n1 | cut -d ' ' -f3 | tr -d '"')
    - mkdir ../fusiondirectory-orchestrator-$VERSION/
    - mv ./* ../fusiondirectory-orchestrator-$VERSION/
    - mv  ../fusiondirectory-orchestrator-$VERSION/ ./
    - tar -cvzf fusiondirectory-orchestrator-$VERSION.tar.gz *
  artifacts:
    paths:
      - ./*.tar.gz
